name: CI

on:
  push:
    branches:
      - gh-actions

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.5
      env:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        RAKE_ENV: test
    steps:
      - uses: actions/checkout@v1
      - name: Bundle
        run: |
          gem install bundler -v 2.0.2
          bundle install
      - name: Run rspec
        run: |
          bundle exec rspec --format progress \
                            --format RspecJunitFormatter
  rubocop:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.5
      env:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        RAKE_ENV: test
    steps:
      - uses: actions/checkout@v1
      - name: Bundle
        run: |
          gem install bundler -v 2.0.2
          bundle install
      - name: Run Rubocop
        run: bundle exec rubocop

  reek:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.5
      env:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        RAKE_ENV: test
    steps:
      - uses: actions/checkout@v1
      - name: Bundle
        run: |
          gem install bundler -v 2.0.2
          bundle install
      - name: Run Reek
        run: bundle exec reek
