name: Release Gem

on:
  push:
    branches:
      - add-release-flow

jobs:
  # bump_tag:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Bump version and push tag
  #     uses: anothrNick/github-tag-action@master
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       WITH_V: true
  #       RELEASE_BRANCHES: 'add-release-flow'
  update_changelog:
    runs-on: ubuntu-latest
    # needs: bump_tag
    steps:
    - uses: actions/checkout@master
    - name: Update Changelog
      run: bash -c "latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`) && git log --reverse $latest_tag..HEAD --oneline --no-decorate --first-parent | nl -w2 -s'. ' | cat - CHANGELOG.md > CHANGELOG.md.tmp && mv CHANGELOG.md.tmp CHANGELOG.md && cat CHANGELOG.md"
  # secrets = ["GITHUB_TOKEN", "SSH_KEY"]
  # args = ["bash", "-c", "{ [ \"$(git rev-parse --abbrev-ref HEAD)\" = \"master\" ] || exit 78; } && rm -rf .github && git add -A .github && git commit -m \"Remove .github\" && git remote set-url origin git@github.com:GITHUB/PROJECT.git && git push --force origin master"]
  # create_gh_release:
  # push_to_gh_packages:
  #   runs-on: ubuntu-latest
  #   needs: bump_tag
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Build and publish gem
  #     uses: jstastny/publish-gem-to-github@master
  #     with:
  #       token: ${{ secrets.GITHUB_TOKEN }}
  #       owner: team-aaa
